### ISSUE TITLE
Search Logging Function

### ISSUE THREAD

**Issue by JonnyNL** [GroupThreeFS/FullStack_GroupThree#10]
We need a logging function that can exported to be used to log the users search queries.

**Create a new branch called LOGGING_FUNC, merge main into LOGGING_FUNC and begin your work**

This logging function is written in utils/log.js

**Example:**
If I login as Jonny and search up "pong" the logging function will create a new file in the logs folder with todays date, in the log folder it will log that query like
`[2023-08-09:01:42pm] Jonny searched for "pong" [# of queries returned]`

**Comment by TylerN132** [comment]
Completed by Tyler Nolan
